// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syvebmqxwekxgamjokel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5dmVibXF4d2VreGdhbWpva2VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTgzNTksImV4cCI6MjA3MTYzNDM1OX0.TW4-xUdB3FQ0gYmQvXJvuJ9ulvrBfbdJ8d10kt6UDaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});